title: Otavio Vargas — Software Engineer
url: 'https://otaviovargasm.github.io'
baseurl: '/otaviovargasm'

description: Resume of Otavio Vargas — Software Engineer | Java | Spring Boot | AWS | Kafka | Kubernetes | SAP
theme_skin: blue
chrome_mobile_color: #0070F2

analytics: G-5XX9CZWFY2

sass:
  sass_dir: _sass
  style: compressed
compress-site: yes

exclude:
  - README.md
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

port: 4000
host: 0.0.0.0
safe: false